blueprint:
  name: "Test – Zeitschaltuhr Zyklus 1"
  domain: automation
  input:
    targets:
      name: Zu steuernde Entitäten
      selector:
        entity:
          multiple: true
          domain:
            - light
            - switch

    c1_on_type:
      name: "Zyklus 1 – Einschalten: Typ"
      default: time
      selector:
        select:
          options:
            - label: Feste Uhrzeit
              value: time
            - label: Sonnenaufgang
              value: sunrise
            - label: Sonnenuntergang
              value: sunset
    c1_on_time:
      name: "Zyklus 1 – Einschalten: Uhrzeit"
      default: "08:00:00"
      selector:
        time: {}
    c1_on_offset:
      name: "Zyklus 1 – Einschalten: Offset (Sonne)"
      default: "00:00:00"
      selector:
        text: {}

    c1_off_type:
      name: "Zyklus 1 – Ausschalten: Typ"
      default: time
      selector:
        select:
          options:
            - label: Feste Uhrzeit
              value: time
            - label: Sonnenaufgang
              value: sunrise
            - label: Sonnenuntergang
              value: sunset
    c1_off_time:
      name: "Zyklus 1 – Ausschalten: Uhrzeit"
      default: "09:00:00"
      selector:
        time: {}
    c1_off_offset:
      name: "Zyklus 1 – Ausschalten: Offset (Sonne)"
      default: "00:00:00"
      selector:
        text: {}

mode: restart

trigger:
  - platform: time
    at: !input c1_on_time
    id: c1_on_time
  - platform: sun
    event: sunrise
    offset: !input c1_on_offset
    id: c1_on_sunrise
  - platform: sun
    event: sunset
    offset: !input c1_on_offset
    id: c1_on_sunset

  - platform: time
    at: !input c1_off_time
    id: c1_off_time
  - platform: sun
    event: sunrise
    offset: !input c1_off_offset
    id: c1_off_sunrise
  - platform: sun
    event: sunset
    offset: !input c1_off_offset
    id: c1_off_sunset

action:
  - variables:
      on_type: !input c1_on_type
      off_type: !input c1_off_type
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['c1_on_time','c1_on_sunrise','c1_on_sunset'] and
                 ((trigger.id.endswith('time') and on_type=='time') or
                  (trigger.id.endswith('sunrise') and on_type=='sunrise') or
                  (trigger.id.endswith('sunset') and on_type=='sunset')) }}
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input targets

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['c1_off_time','c1_off_sunrise','c1_off_sunset'] and
                 ((trigger.id.endswith('time') and off_type=='time') or
                  (trigger.id.endswith('sunrise') and off_type=='sunrise') or
                  (trigger.id.endswith('sunset') and off_type=='sunset')) }}
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input targets
